kafka:
  auto-create-topics: true
  bootstrap-servers: localhost:9092
  pool-timeout: 1_000
  auto-commit: false
  consumers:
    orders-commands:
      auto-offset-reset: earliest
      concurrency: 1
      id: kafka-listener-orders-commands-${INSTANCE_ID:1}
      topics:
        - place_order-command-topic
      group-id: orders-commands-group
      max-attempts: 4
      auto-create-topics: false
    orders-external-events:
      auto-offset-reset: earliest
      concurrency: 1
      id: kafka-listener-orders-external-events-${INSTANCE_ID:1}
      topics:
        - shipping-cost-calculated-external-event-topic
      group-id: orders-external-events-group
      max-attempts: 4
      auto-create-topics: false

server:
  port: 8080
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  undertow:
    threads:
      worker: 64
      io: 4

spring:
  flyway:
    enabled: false
  datasource:
    url: jdbc:mysql://${mysql.url}/${mysql.schema}?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${mysql.username}
    password: ${mysql.password}
    hikari:
      auto-commit: false
      connection-timeout: 250
      max-lifetime: 600000
      maximum-pool-size: 20
      minimum-idle: 10
      pool-name: master
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      "[hibernate.dialect]": org.hibernate.dialect.MySQLDialect
      "[hibernate.generate_statistics]": false
      "[hibernate.connection.provider_disables_autocommit]": true
      hibernate:
        jdbc:
          batch_size: 10
        order_inserts: true
        order_updates: true