kafka:
  consumers:
    orders-commands:
      auto-create-topics: true
    orders-external-events:
      auto-create-topics: true

server:
  undertow:
    threads:
      worker: 10
      io: 2

logging:
  level:
    com.kaua.order.infrastructure: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/order?useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration