name: Push to main/develop and generate coverage badge and run CD

on:
  push:
    branches:
      - develop
      - main
  workflow_dispatch:

jobs:
  generate-badge-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate coverage for DOMAIN
        run: ./gradlew :domain:jacocoTestReport

      - name: Upload coverage DOMAIN to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          COVERALLS_FLAG_NAME: 'DOMAIN'
        run: ./gradlew coverallsJacoco

      - name: Generate coverage aggregation
        run: ./gradlew jacocoTestReport

      - name: Upload coverage to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          COVERALLS_FLAG_NAME: 'global'
        run: ./gradlew coverallsJacoco