name: Push to main/develop and generate coverage badge and run CD

on:
  push:
    branches:
      - develop
      - main
  workflow_dispatch:

jobs:
  generate-badge-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # - name: Generate coverage for DOMAIN
      #   run: ./gradlew :domain:test

      # - name: Upload coverage DOMAIN to Codecov
      #   uses: codecov/codecov-action@v4.5.0
      #   with:
      #     directory: domain/build/reports/jacoco/test
      #     files: ./jacocoTestReport.xml
      #     flags: domain-module
      #     name: domain-module
      #     fail_ci_if_error: true
      #     token: ${{ secrets.CODECOV_TOKEN }}

      - name: Generate coverage aggregation
        run: ./gradlew jacocoTestReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./build/reports/jacoco/test/jacocoTestReport.xml
          flags: global
          name: global
          verbose: true
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

#
#      - name: Upload coverage DOMAIN to Coveralls
#        env:
#          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
#          COVERALLS_FLAG_NAME: 'DOMAIN'
#        run: ./gradlew :domain:coverallsJacoco
#
#      - name: Generate coverage aggregation
#        run: ./gradlew jacocoTestReport
#
#      - name: Upload coverage to Coveralls
#        env:
#          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
#          COVERALLS_FLAG_NAME: 'global'
#        run: ./gradlew coverallsJacoco
